### ISSUE TITLE
[Discuss]Suggests upgrading some depdencies to avoid error when using MySQL 8 with utf8mb4 charset.

### ISSUE THREAD

**Issue by leeoo** [CoderCharm/fastapi-mysql-generator#12]
Got "ERROR 1366 (HY000): Incorrect string value..." error when running app using MySQL 8.0.23 with utf8mb4 charset.
Error would be gone after upgrading below dependencies.

PyMySQL==1.0.2
SQLAlchemy==1.4.6

**Comment by wxy2077** [comment]
Thanks!  #13
