### ISSUE TITLE
redis初始化发现了一点点小问题

### ISSUE THREAD

**Issue by LvPeng990324** [CoderCharm/fastapi-mysql-generator#16]
作者您好，我在阅读您的框架代码，发现了这个小问题，在这里提醒一下~

![image](https://user-images.githubusercontent.com/37319644/119788952-2ddafc80-bf05-11eb-8cb0-da07e46c26fb.png)

**Comment by wxy2077** [comment]
哈哈哈，感谢提醒，如果方便的话，你可以提个PR ，或者我下班后回去后才有时间。😃

突然发现这个超时参数配置应该放在配置文件里面，后面考虑配置文件该用 yaml。
