### ISSUE TITLE
response_model vs. resp_200

### ISSUE THREAD

**Issue by grayguest** [CoderCharm/fastapi-mysql-generator#2]
response_model是fastapi自带的https://fastapi.tiangolo.com/tutorial/response-model/
resp_200是作者写的

这两者应该怎么能兼容一下呢？作者是抛弃了response_model吗，就是有的时候需要人工convert了，比如sqlalchemy返回的对象不能直接用于resp_200中的data键

**Comment by wxy2077** [comment]
是的，我没有准备用`response_model`这个响应，我感觉这个太麻烦了。

> 比如sqlalchemy返回的对象不能直接用于resp_200中的data键。

这个问题我也注意到了，暂时可以这样解决。
```py
def resp_200(*, data: Union[list, dict, str] = None, message: str = "Success") -> dict:
    # return JSONResponse(
    #     status_code=status.HTTP_200_OK,
    #     content={
    #         'code': 200,
    #         'message': message,
    #         'data': data,
    #     }
    # )
    return {
            'code': 200,
            'message': message,
            'data': data,
        }

```
但是`sqlalchemy`查询后的对象，FastAPI自动序列化JSON，感觉不是很友好，时间对象和浮点对象转换会有问题。

**Comment by grayguest** [comment]
https://fastapi.tiangolo.com/tutorial/encoder/，
好像用jsonable_encoder包装一下就能用你的那个函数了，不过这个函数名字让人觉得json encode，以为返回得是str类型，结果是dict list 这种

**Comment by wxy2077** [comment]
🥳 感谢老哥，我晚上回去看看这个方法，或者老哥可以直接提PR 🤗。
