### ISSUE TITLE
common.sys_schedule.py应该用单例模式实现，现在使用的时候会在使用的时候被覆盖掉

### ISSUE THREAD

**Issue by bill-qubitx** [CoderCharm/fastapi-mysql-generator#23]
class ScheduleCli:

    _instance = None
    def __new__(cls, *args, **kw):
        if cls._instance is None:
            cls._instance = object.__new__(cls, *args, **kw)
        return cls._instance

如果不加单例，调用的时候时候会重新import，会覆盖fastapi启动的时候实例化的对象

**Comment by wxy2077** [comment]
嗯，是的，我之前也有过类似的想法， [here](https://github.com/CoderCharm/fastapi-mysql-generator/blob/13a7e98cd663abbbaf157d22375d15d6269eebbb/%7B%7Bcookiecutter.project_name%7D%7D/common/logger.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L18) 但还是没加， 有空再加。

**Comment by wxy2077** [comment]
现在已经加上了
