### ISSUE TITLE
全局捕获异常失败

### ISSUE THREAD

**Issue by ron-wang1** [CoderCharm/fastapi-mysql-generator#29]
项目环境:centos7
python版本:3.9.9
问题描述:
生成项目之后我在api/v1/items.py写了一个简单的测试接口
```python
@router.get("/demo", name="测试demo")
def items_test() -> Any:
    raise TypeError("demo")
```

请求之后并没有被server中注册的@app.exception_handler(Exception)捕获到

**Comment by ron-wang1** [comment]
用中间件解决了...

**Comment by ssrshz** [comment]
> 

方便告知下，怎么解决的吗
