### ISSUE TITLE
[BUG]examples/demo_scheduler/main.py

### ISSUE THREAD

**Issue by grayguest** [CoderCharm/fastapi-mysql-generator#3]
https://github.com/CoderCharm/fastapi-mysql-generator/blob/master/examples/demo_scheduler/main.py#L110
应该去掉参数`next_run_time=datetime.now()`，因为如果加上就会立即运行，有悖于固定时间运行。
是应该加到`async def add_cron_job`函数里面？

**Comment by wxy2077** [comment]
嗯，这里应该是当时笔误，写错地方了，谢谢提醒，晚上回去改。
