### ISSUE TITLE
[Problem] variable basedir in logger.py 

### ISSUE THREAD

**Issue by grayguest** [CoderCharm/fastapi-mysql-generator#7]
```python
# basedir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
basedir = os.path.dirname(os.path.dirname((os.path.dirname(os.path.abspath(__file__)))))
```
这块basedir因为是按照相对位置硬编码的，如果相对位置发生变化，`from logger import logger`生成日志的位置就会有问题，请问作者这块有啥好的解决方案吗？

**Comment by wxy2077** [comment]
日志的路径考虑 后面考虑放到项目配置信息里面。我现在大部分的项目规划模版都在参考 [gin-vue-admin](https://github.com/flipped-aurora/gin-vue-admin) 这个项目的服务端。

**Comment by grayguest** [comment]
我觉得这个问题不在于配置信息写在哪儿，而是配置信息怎么写，因为都是用的相对路径来计算生成日志的位置，如果调用方不符合预期的相对路径，那生成日志的位置也就不预期了，可能需要运行时的项目根目录信息。。

**Comment by wxy2077** [comment]
嗯，这个问题我也注意到了，我的意思是，配置信息里面之前有相对启动文件`main.py`计算的项目路径 `BASE_PATH`，只要配置文件路径和启动文件不变动，这个`BASE_PATH`始终是可以定位到项目根路径的 (`Django`里面`BASE_DIR`就是这样设计的)

**Comment by grayguest** [comment]
```
basedir = os.path.dirname(os.path.dirname((os.path.dirname(os.path.abspath(__file__)))))
```
我今天才发现__file__不受调用方影响，我以为调用的时候__file__是指向调用方呢。
