### ISSUE TITLE
日志优化求助

### ISSUE THREAD

**Issue by Macolm6** [CoderCharm/fastapi-mysql-generator#8]
帮忙看下怎么配置https://juejin.cn/post/6844904187046658062，我试了一下有报错
![image](https://user-images.githubusercontent.com/56667336/106289196-f07e9f00-6283-11eb-9d15-b6f667283d43.png)

**Comment by wxy2077** [comment]
emmm..... 上面那篇文章也不是我写的，我这个项目直接用的 第三方日志库 [loguru](https://github.com/Delgan/loguru) 

至于记录请求id，你可以在 middleware 和 request请求对象上 记录。  文章里面的那位大佬封装原生的日志模块，我感觉好复杂，应该挺厉害的，但是直接使用第三方 别人封装好的这个日志模块我感觉 就够了，而且操作简单。

**Comment by Macolm6** [comment]
好的，谢谢

**Comment by gitnote-images** [comment]
不影响使用
